### ISSUE TITLE
TODO list for publication ready (v1 release)

### ISSUE THREAD

**Issue by Miachol** [hiplot/gold#184]
- [ ] check and clean issues
- [ ] check and fix all exported RData for correct plots in local
- [ ] check the correctness of the result and give a certification report for all plugins
- [ ] update plugins document and add English video tutorial
- [ ] add more statistical test (Chi-square test, Fisher's exact test......)
- [ ] add more ML models train (logistic regression, decision tree, random forest, XGBoost)
- [ ] add more ML models predict (expression subtypes; mutation status; risk score)
- [ ] improve the hctl for a long time tasks
- [ ] collect and add new visualization methods (10+ at least)
- [ ] ......

**Comment by ShixiangWang** [comment]
这个具体还有哪些要优化的呢
